/**
 * Logic for Saving, Creating, and Updating SAP Objects via MCP.
 * Decoupled from the UI to allow reuse.
 */

export const unLockObject = async (objectUrl, lockHandle, callMcpTool, setStatus) => {
    if (lockHandle) {
        setStatus({ type: 'info', msg: 'Cleaning up: Unlocking...' });
        try {
            await callMcpTool('unLock', { objectUrl, lockHandle });
            console.log("Unlocked!");
        } catch (unlockErr) {
            console.error("Unlock failed:", unlockErr);
        }
    }
};

// Helper to format syntax errors
const formatErrors = (errors) => errors.map(e => `[ERROR] Line ${e.line}: ${e.text}`);

export const updateObject = async (objectName, objectUrl, sourceCode, transport, callMcpTool, setStatus) => {
    const objectSourceUrl = `${objectUrl}/source/main`;
    let lockHandle = null;

    try {
        setStatus({ type: 'info', msg: 'Update: Locking...' });

        // 1. LOCK
        const lockRes = await callMcpTool('lock', { objectUrl, accessMode: 'MODIFY' });
        if (!lockRes || !lockRes.lockHandle) {
            throw new Error("Lock failed. Object might be locked by another user.");
        }
        lockHandle = lockRes.lockHandle;
        console.log("Locked:", lockHandle);

        // 2. SET SOURCE
        setStatus({ type: 'info', msg: 'Update: Setting Source...' });
        await callMcpTool('setObjectSource', {
            objectSourceUrl,
            source: sourceCode,
            lockHandle,
            transport
        });
        console.log("Source Set!");

        // 3. SYNTAX CHECK 
        setStatus({ type: 'info', msg: 'Update: Checking Syntax...' });
        const syntaxCheckRes = await callMcpTool('syntaxCheckCode', {
            code: sourceCode,
            url: objectSourceUrl,
            mainUrl: objectSourceUrl
        });

        let syntaxErrors = [];
        if (syntaxCheckRes && syntaxCheckRes.result) {
            if (Array.isArray(syntaxCheckRes.result)) {
                syntaxErrors = syntaxCheckRes.result.filter(m => m.severity === 'E');
            }
        } else if (Array.isArray(syntaxCheckRes)) {
            syntaxErrors = syntaxCheckRes.filter(m => m.severity === 'E');
        }

        if (syntaxErrors.length > 0) {
            const errorList = formatErrors(syntaxErrors);
            setStatus({ type: 'error', msg: 'Syntax Check Failed' });
            await unLockObject(objectUrl, lockHandle, callMcpTool, setStatus);
            return { success: false, errors: errorList };
        }

        // 4. ACTIVATE (Simplistic activation for now)
        setStatus({ type: 'info', msg: 'Update: Activating...' });
        await callMcpTool('activateByName', { objectName, objectUrl });

        setStatus({ type: 'success', msg: 'Update Complete' });
        return { success: true, errors: [] };

    } catch (e) {
        console.error("Update Flow Error:", e);
        setStatus({ type: 'error', msg: e.message });
        return { success: false, errors: [e.message] };
    } finally {
        // 5. UNLOCK 
        await unLockObject(objectUrl, lockHandle, callMcpTool, setStatus);
    }
};

export const createObject = async (objectType, objectName, pkg, transport, sourceCode, callMcpTool, setStatus) => {
    try {
        // Map common types
        let adtType = objectType;
        if (objectType === 'CLAS') adtType = 'CLAS/OC';

        // 1. Search for Package
        setStatus({ type: 'info', msg: `Create: Searching for package ${pkg}...` });
        const pkgSearchRes = await callMcpTool('searchObject', { query: pkg.toUpperCase() });

        let parentPath = '';
        if (pkgSearchRes && pkgSearchRes.results) {
            const pkgMatch = pkgSearchRes.results.find(res => res["adtcore:name"] === pkg.toUpperCase());
            if (pkgMatch) parentPath = pkgMatch["adtcore:uri"];
        }

        if (!parentPath) parentPath = `/sap/bc/adt/packages/${pkg.toLowerCase()}`;

        // 2. Create Object
        setStatus({ type: 'info', msg: `Create: Creating ${objectName} (${adtType})...` });
        await callMcpTool('createObject', {
            objtype: adtType,
            name: objectName.toUpperCase(),
            parentName: pkg.toUpperCase(),
            description: 'Generated by OctoAgent',
            parentPath: parentPath,
            transport: transport
        });

        // 3. Construct URL
        const objectUrl = `/sap/bc/adt/oo/classes/${objectName.toLowerCase()}`;

        // 4. Update Workflow
        return await updateObject(objectName, objectUrl, sourceCode, transport, callMcpTool, setStatus);

    } catch (e) {
        return { success: false, errors: ["Create Flow Error: " + e.message] };
    }
};

export const saveToSap = async (inputs, callMcpTool, setStatus) => {
    const { objectName, package: pkg, transport, sourceCode, objectType } = inputs;
    const objectUrl = `/sap/bc/adt/oo/classes/${objectName.toLowerCase()}`;

    // Result Template
    const result = {
        objectName,
        objectType: objectType || 'CLAS', // Ensure we pass this from inputs if available
        success: false,
        errors: [],
        sourceCode
    };

    try {
        setStatus({ type: 'info', msg: 'Checking object existence...' });

        // 1. CHECK EXISTENCE
        let exists = false;
        try {
            const searchRes = await callMcpTool('searchObject', { query: objectName.toUpperCase() });
            if (searchRes && Array.isArray(searchRes.results)) {
                exists = searchRes.results.some(obj =>
                    obj["adtcore:name"] === objectName.toUpperCase() &&
                    (obj["adtcore:type"] === 'CLAS/OC' || obj["adtcore:type"] === 'CLAS')
                );
            }
        } catch (e) {
            exists = false;
        }

        let opResult;
        if (exists) {
            const confirm = window.confirm(`Object ${objectName} exists. Update?`);
            if (!confirm) {
                setStatus({ type: 'info', msg: 'Cancelled' });
                return { ...result, errors: ['Cancelled by user'] };
            }
            opResult = await updateObject(objectName, objectUrl, sourceCode, transport, callMcpTool, setStatus);
        } else {
            opResult = await createObject(objectType, objectName, pkg, transport, sourceCode, callMcpTool, setStatus);
        }

        return { ...result, ...opResult };

    } catch (e) {
        setStatus({ type: 'error', msg: e.message });
        return { ...result, success: false, errors: [e.message] };
    }
};
